import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Providers} from "@/app/providers";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type ToasterProps = React.ComponentProps<typeof Toaster>;

const toastOptions: ToasterProps = {
  theme: "dark",
  richColors: true,
  closeButton: true,
  pauseWhenPageIsHidden: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Toaster {...toastOptions} />
      <Providers>
        {children}
      </Providers>
      </body>
    </html>
  );
}
